"""Compile agent findings into a structured Markdown report and write report.md."""

import pathlib
from datetime import datetime
from models.schemas import ReportResult


def write_report(
    file_path: str,
    query: str,
    summary: str,
    keywords: str,
    sentiment: str,
    analysis: str,
) -> ReportResult:
    """Assemble all tool outputs into a formatted Markdown report saved as report.md."""
    md = f"""# File Analysis Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**File:** `{file_path}`
**Query:** {query}

---

## Summary
{summary}

## Keywords & Topics
{keywords}

## Sentiment
{sentiment}

## Analysis
{analysis}

---
*Generated by File Analysis Agent*
"""
    out = pathlib.Path("report.md")
    out.write_text(md)
    return ReportResult(report_path=str(out.resolve()), markdown=md)
